### ISSUE TITLE
The preview location in DockMate does not account for the dock's position on the screen (bottom, left, or right)

### ISSUE THREAD

**Issue by KevOBrien** [MacEnhance/MacForge#53]
## Bug Report

**Current Behavior**
The DockMate plugin is only designed to work correctly when the dock is located at the bottom of the screen. If the dock is positioned on the left or right of the screen, there is some unwanted behaviour. 

For example, the previews can be shown 50px from the dock. If the dock is at the bottom of the screen, this would mean that the preview will be 50px above the dock. However, when the dock is on the left side of the screen, one would expect this offset to be to the right side of the dock, but it is still an offset above the icon.

Even more annoyingly, since the preview now appears above the icon, and not to its side, if I then move my mouse upwards to move over the preview, the mouse is actually moving over another icon in the dock, so the preview then changes to this other icon. This is super annoying with the Spotify preview where I want to pause or skip a song, but as I move my mouse to the Spotify preview, the preview changes to that of the icon above Spotify.

**To Reproduce**
Set the Mac's dock to the left of the screen and then notice the behaviour outlined above.

**Expected behavior/code**
I would expect the locations of the preview to be relative to where on the screen the dock is placed. If the dock is at the bottom, then the previews should be placed above the icons as it is now. However, if the dock is at the left or right of the screen then I would expect the previews to be placed to the right or left of the icons, respectively.

**Screenshots**
![image](https://user-images.githubusercontent.com/16003438/101351390-f66e8a00-38a9-11eb-814b-ef44a8d0d383.png)

**Environment**
- MacForge version(s): 1.0.8
- OS version: 11.0.1
- Plugins: DockMate

**Comment by KevOBrien** [comment]
Better screenshot for reference:

![image](https://user-images.githubusercontent.com/16003438/101351287-d2ab4400-38a9-11eb-8df6-f6d7de40c874.png)

**Comment by w0lfschild** [comment]
Hmm that's odd it's also definitely a bug that the Text is black there. I'll look into it.

**Comment by w0lfschild** [comment]
Okay I see what the issue is, has to do with the orientation. It'll be fixed in the next version.

**Comment by w0lfschild** [comment]
This is fixed in DockMate 0.8+

**Comment by a-ludwig1980** [comment]
I think the bug is not solved....

<img width="604" alt="Bildschirmaufnahme 2022-11-03 14 05 39" src="https://user-images.githubusercontent.com/117365381/199728246-c40da132-1fe0-4370-b360-b03365002776.png">
